source = colors.conf

exec-once = scripts/generate-hyprland-conf-d
source = ~/.config/hypr/hyprland.conf.d/source-all.conf

monitor = ,preferred,auto,1

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    initial_workspace_tracking = 1
}

general {
    gaps_in = 10
    gaps_out = 14
    border_size = 3
    col.active_border = $primary
    col.inactive_border = rgba(00000000)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = on
        ignore_opacity = true
        xray = true
    }

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = 0x66000000
    }
}

animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, once
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

dwindle {
    pseudotile = true
    preserve_split = true
}

gestures {
    gesture = 3, horizontal, workspace
}

binds {
    workspace_back_and_forth = false
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}
