position: "top"
anchor_to_edges: true
height: 28
start:
  - type: "workspaces"
    icon_size: 16
  - type: "focused"
    icon_size: 16
  - type: "label"
    label: ""
    class: "right edge"
center: [ ]
end:
  - type: "label"
    label: ""
    class: "left edge"
  - type: "tray"
    icon_size: 16
  - type: "clock"
    format: "%Y-%m-%dT%H:%M:%S%:z"
    disable_popup: true
  - type: "script"
    cmd: "${XDG_CONFIG_HOME:-$HOME/.config}/hypr/scripts/get-active-keyboard-layout"
    mode: "watch"
    interval: 100
