hl.on("hyprland.start", function ()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("ironbar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("sleep 2 && $HOME/.config/hypr/scripts/randomize-background")
end)
