#!/usr/bin/env bash

conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}"/hypr/hyprland.conf.d
out_file="$conf_dir/source-all.conf"

mkdir -p "$conf_dir"
: > "$out_file"

find "$conf_dir" -name "*.conf" ! -path "$out_file" | sort | while read -r file; do
    echo "source = $file" >> "$out_file"
done
